apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-srlp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-srlp
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-srlp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-srlp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-srlp
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-kwvc-tenant/rhtap-demo-app/hacbs-test-project-srlp@sha256:de71ed1ce807f2d04d6168c39f32087f9b114af0dad361657ccab408cc8b9693
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
